# Default values

# ------------------------------------------------------------------------------
# S3PVC-CLAIM:
#persistenceVolumeClaim for airflow and druid-components
# ------------------------------------------------------------------------------

# volumeclaim :
#   bucket: airflow-dags
#   secret: cos-write-access
#   # claim: s3pvc ----> #hardcode in PVC
#   # access_mode: ReadWriteOnce ----> #hardcode in PVC
#   # size: "1000Gi" #hardcode
#   # storageclass: ibmc-s3fs-standard-regional ----> #hardcode in PVC

# # ------------------------------------------------------------------------------
# # ingress:
# # ------------------------------------------------------------------------------
# ingress:
#   name: airflow-ingress
#   host: ui.asset-forome-dev-162fa491ef10b14d22843708d94ef0ba-0000.us-south.containers.appdomain.cloud
#   certificate: asset-forome-dev-162fa491ef10b14d22843708d94ef0ba-0000 
#   #oc get secrets -n openshift-ingress - view secrets with TLC-certificates

airflow:
  project: airflow
  name: airflow
  git_uri: https://github.com/ForomePlatform/airflow-cwl-docker.git
  git_branch: master
  output_registry: image-registry.openshift-image-registry.svc:5000
  # airflow_volumes:
  #   workdir_volume: airflow-workdir
  #   workdir_claim_name: airflow-workdir-claim