apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: {{ .Values.airflow.name }}
spec:
  runPolicy: Serial
  strategy:
  source:
    type: Git
    git:
      uri: {{ .Values.airflow.git_uri }}
      ref: {{ .Values.airflow.git_branch }}
    type: Docker
    dockerStrategy: 
      noCache: false
      dockerfilePath: Dockerfile
    # sourceStrategy:
      # env:
      # - name: POSTGRE_SERVER
      #   valueFrom:
      #     configMapKeyRef:
      #       key: airflow-cm-build
      #       name: postgre_server
      # - name: POSTGRE_DB
      #   valueFrom:
      #     configMapKeyRef:
      #       key: airflow-cm-build
      #       name: postgre_db
      # - name: POSTGRE_USER
      #   valueFrom:
      #     secretKeyRef:
      #       key: airflow-sec-build
      #       name: username
      # - name: POSTGRE_PASS
      #   valueFrom:
      #     secretKeyRef:
      #       key: airflow-sec-build
      #       name: username
      buildArgs:
        - name: POSTGRE_SERVER
          value: "postgres"
        - name: POSTGRE_DB
          value: "airflow"
        - name: POSTGRE_USER
          value: "airflow"
        - name: POSTGRE_PASS
          value: "airflow"
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.airflow.name }}:latest"
