apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: {{ .Values.airflow.name }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.airflow.git_uri }}
      ref: {{ .Values.airflow.git_branch }}
  strategy:
    sourceStrategy:
      env:
    - name: "POSTGRE_SERVER"
      value: "postgres"
    - name: "POSTGRE_DB"
      value: "airflow"
    - name: "POSTGRE_USER"
      value: "airflow"
    - name: "POSTGRE_PASS"
      value: "airflow"
    type: Docker
    dockerStrategy:
      noCache: false
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.airflow.name }}:latest"
